### ISSUE TITLE
OT papers

### ISSUE THREAD

**Issue by streamich** [ept/crdt-website#114]
Issue on: https://github.com/ept/crdt-website/tree/gh-pages/papers.html

OT is an alternative approach for distributed state synchronization to CRDT. Also, the first CRDT algorithm, the WOOT algorithm (Without OT), was proposed as a direct alternative to OT.

Given the above, for historic completeness, would you agree to allow creation of "OT" section, which would list OT papers?

**Comment by ept** [comment]
Hi @streamich, you're right that OT solves a similar problem, but it's also quite a different category of algorithms. My suggestion would be that we link to [OTFAQ](https://www3.ntu.edu.sg/scse/staff/czsun/projects/otfaq/), which already has a list of OT papers. We could consider maintaining a list ourselves, but I'd be inclined to put it on a separate page and not mix it up with the CRDT papers. Would you be interested in creating and maintaining such a list?

**Comment by streamich** [comment]
> [..] I'd be inclined to put it on a separate page and not mix it up with the CRDT papers.

Yes, I also was thinking that OT papers would have their own page/tag.

Thank you for the OTFAQ link.

> Would you be interested in creating and maintaining such a list?

I was thinking about creating an initial OT paper list, but I see OTFAQ is more comprehensive than what I have. I guess, indeed, is is better to direct users there for now.
