### ISSUE TITLE
Deployment failed due to GitHub Actions outage

### ISSUE THREAD

**Issue by jryans** [ept/crdt-website#55]
As shown on the [actions list](https://github.com/ept/crdt-website/actions), the PRs merged today failed to deploy, likely due to a GitHub Actions [outage](https://www.githubstatus.com/incidents/sks5ctnwcxsb):

![image](https://user-images.githubusercontent.com/279572/159477319-52ea249d-c413-4a69-aa76-d6c6403f2045.png)

The outage is now resolved, so hopefully deployment should work now. I believe @ept could go to the [most recent run](https://github.com/ept/crdt-website/actions/runs/2021824503) and click "Re-run all jobs" on the top right (only available to those with repo access).

**Comment by ept** [comment]
Thanks for pointing this out! I requested a re-run several hours ago but it's still listed as "queued" and seems to have made no progress. Maybe the outage is not quite over yet after all, despite the status page being all green…

**Comment by jryans** [comment]
Ah yeah, there's now a [new outage](https://www.githubstatus.com/incidents/83lq7ftk19r5) affecting even more things... 😅 Anyway, at least it's queued, so perhaps it will eventually re-run as things recover.

**Comment by jryans** [comment]
Well, looks like the actions failed, but the site changes got deployed anyway, so let's call that fixed! 😅

**Comment by ept** [comment]
On merging your latest PR it also seems to have deployed fine 👍
