### ISSUE TITLE
I think Figma shouldn't technically be described as a CRDT

### ISSUE THREAD

**Issue by aboodman** [ept/crdt-website#60]
First, thanks for creating this site. Super useful.

Second, in a few places you refer to Figma as using CRDTs. They themselves say this is not the case in the document you refer to:

> Figma isn't using true CRDTs though. CRDTs are designed for decentralized systems where there is no single central authority to decide what the final state should be. There is some unavoidable performance and memory overhead with doing this. Since Figma is centralized (our server is the central authority), we can simplify our system by removing this extra overhead and benefit from a faster and leaner implementation.

I think this distinction is important. If what Figma is doing is a CRDT, then Replicache, Fluid Framework, and similar approaches would also be considered CRDTs.

But that doesn't seem right -- what Replicache and FF do are clearly not CRDTs, and therefore it's not correct to refer to Figma as using CRDTs either (unless you have more up to date info than that blog post).

**Comment by ept** [comment]
Hi @aboodman, I agree that Figma shouldn't be considered a CRDT, and we should make this clearer. In 112568b39d77ab919c9110f4c63c347da5d2ba87 I've updated the text of the two places on this site where we refer to Figma. Do you think this is better?

**Comment by aboodman** [comment]
Yep, sorry for slow reply.
