### ISSUE TITLE
Broken 'Optimistic Replication' link in CRDT Glossary

### ISSUE THREAD

**Issue by krahul3790** [ept/crdt-website#67]
In the CRDT Glossary section, under Optimistic replication subsection, 
"See [Optimistic Replication](https://core.ac.uk/download/pdf/22879037.pdf) by Yasushi Saito and Marc Shapiro."  the link seems to be broken.

https://core.ac.uk/download/pdf/22879037.pdf

**Comment by ept** [comment]
Thanks for letting us know! I fixed this in 7dcca486a00b689fe42d34caf2301a657197dcc5
