### ISSUE TITLE
Add missing papers

### ISSUE THREAD

**Issue by alishoker** [ept/crdt-website#77]
Issue on: https://github.com/ept/crdt-website/tree/gh-pages/pages/index.md

Please add these:
Best paper DAIS'21: https://link.springer.com/chapter/10.1007/978-3-030-78198-9_4

LightKone LiRA: https://www.researchgate.net/publication/347522020_LightKone_Reference_Architecture_LiRA

Thanks.

**Comment by ept** [comment]
Thanks for the pointers Ali, added in 85cd535576065f3f805a73a224d78fe937b13dc1
